server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    #eureka? registry? ???? ??
    register-with-eureka: false
    #registry? ?? ??? ???? ??
    retch-registry: false